// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5638.TenkRobit.subsystems;

import org.usfirst.frc5638.TenkRobit.Robot;
import org.usfirst.frc5638.TenkRobit.RobotMap;
import org.usfirst.frc5638.TenkRobit.commands.*;


import com.ctre.MotorControl.CANTalon;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;


import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class driveSub extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon leftMotor1 = RobotMap.left1;
    private final CANTalon leftMotor2 = RobotMap.left2;
    private final CANTalon rightMotor1 = RobotMap.right1;
    private final CANTalon rightMotor2 = RobotMap.right2;
    RobotDrive robotDrive = new RobotDrive(leftMotor1, leftMotor2, rightMotor1, rightMotor2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new driveCom());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    double throttle = Robot.oi.xbox.getRawAxis(2 + 3);
    double turn = Robot.oi.xbox.getRawAxis(-1) * Robot.oi.xbox.getRawAxis(1);
    
    public void takeJoystickInputs(Joystick xbox) {
    	robotDrive.arcadeDrive(throttle, turn);
    }
}

